# Generated by Django 4.2.13 on 2024-06-14 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='book_media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='adminpanelapp.author'),
            preserve_default=False,
        ),
    ]
