# Generated by Django 4.2.13 on 2024-06-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0002_author_book_image_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='book_media/'),
        ),
    ]
